server {
       listen 8080;
       listen [::]:8080;

       server_name 221.121.4.105;

       root /var/www/devops-hackathon-de003-anhaidung/src;
       index index.html;

       access_log /var/log/nginx/anhaidung-k24cntt2.access.log;
       error_log /var/log/nginx/anhaidung-k24cntt2.error.log;

       location / {
           try_files $uri$uri/ =404;
       }
   }
